update

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -5,64 +5,64 @@ on:
     branches:
       - main
 
-jobs:
-  deploy:
-    name: Terraform + Ansible Deployment
-    runs-on: ubuntu-latest
+# jobs:
+#   deploy:
+#     name: Terraform + Ansible Deployment
+#     runs-on: ubuntu-latest
 
-    env:
-      AWS_REGION: us-east-1
+#     env:
+#       AWS_REGION: us-east-1
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v3
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+#       - name: Configure AWS Credentials
+#         uses: aws-actions/configure-aws-credentials@v3
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ env.AWS_REGION }}
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.7.5
+#       - name: Set up Terraform
+#         uses: hashicorp/setup-terraform@v3
+#         with:
+#           terraform_version: 1.7.5
 
-      - name: Terraform Init
-        run: |
-          cd terraform
-          terraform init
+#       - name: Terraform Init
+#         run: |
+#           cd terraform
+#           terraform init
 
 
-      - name: Wait for AWS resources cleanup
-        run: sleep 20
+#       - name: Wait for AWS resources cleanup
+#         run: sleep 20
 
-      - name: Terraform Plan and Apply
-        run: |
-          cd terraform
-          terraform plan -out=tfplan
-          terraform validate  
-          terraform apply -auto-approve tfplan
+#       - name: Terraform Plan and Apply
+#         run: |
+#           cd terraform
+#           terraform plan -out=tfplan
+#           terraform validate  
+#           terraform apply -auto-approve tfplan
 
-      - name: Export EC2 public IP (safe)
-        run: |
-            cd terraform
-            sleep 30
-            echo "Waiting for EC2 instance to be ready..."
-            IP=$(terraform output -raw public_ip 2>/dev/null || echo "")
-            if [ -z "$IP" ]; then
-              echo "EC2 public IP not found. Exiting."
-              exit 1
-            fi
-            echo "EC2_IP=$IP" >> "$GITHUB_ENV"
+#       - name: Export EC2 public IP (safe)
+#         run: |
+#             cd terraform
+#             sleep 30
+#             echo "Waiting for EC2 instance to be ready..."
+#             IP=$(terraform output -raw public_ip 2>/dev/null || echo "")
+#             if [ -z "$IP" ]; then
+#               echo "EC2 public IP not found. Exiting."
+#               exit 1
+#             fi
+#             echo "EC2_IP=$IP" >> "$GITHUB_ENV"
       
         
 
-      - name: Save EC2 IP for Ansible
-        run: |
-          echo "[web]" > ../inventory.ini
-          echo "$EC2_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../inventory.ini
+#       - name: Save EC2 IP for Ansible
+#         run: |
+#           echo "[web]" > ../inventory.ini
+#           echo "$EC2_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../inventory.ini
 
   ansible:
     name: Ansible Configuration
@@ -81,6 +81,14 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+      - name: List repo files
+        run: ls -la
+
+      - name: List files in parent dir
+        run: |
+          ls -la ..
+          cd ansible 
+          ls -la
 
       - name: Ping server
         run: ansible all -i ../inventory.ini -m ping
